# Generated by Django 4.1.dev20220407055456 on 2022-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btdetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('BatType', models.CharField(max_length=200)),
                ('MaxVolt', models.IntegerField(max_length=200)),
                ('MinVolt', models.IntegerField(max_length=200)),
                ('MaxAmp', models.IntegerField(max_length=200)),
                ('MinAmp', models.IntegerField(max_length=200)),
                ('SCMaxVolt', models.IntegerField(max_length=200)),
                ('SCMinVolt', models.IntegerField(max_length=200)),
                ('Temp', models.IntegerField(max_length=200)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
                ('Manf_ID', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'batdetail',
            },
        ),
        migrations.CreateModel(
            name='EMmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
