# Generated by Django 3.2 on 2022-04-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0002_alter_btdetail_maxamp_alter_btdetail_maxvolt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdetail',
            name='BatType',
            field=models.CharField(choices=[('1', 'Lithium Batteries'), ('2', 'Alkaline Batteries'), ('3', 'Carbon Zinc Batteries'), ('4', 'Silver Oxide Batteries'), ('5', 'Zinc Air Batteries')], default=1, max_length=20),
        ),
    ]
