# Generated by Django 2.2.10 on 2022-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0003_alter_btdetail_battype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdetail',
            name='BatType',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='emmodels',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
