# Generated by Django 2.2.10 on 2022-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0004_auto_20220512_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdetail',
            name='MaxAmp',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MaxVolt',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinAmp',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinVolt',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMaxVolt',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMinVolt',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Temp',
            field=models.IntegerField(max_length=10),
        ),
    ]
