# Generated by Django 2.2.10 on 2022-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0006_auto_20220512_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='btdetail',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
