# Generated by Django 4.0.4 on 2022-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0007_btdetail_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emmodels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
