# Generated by Django 4.0.4 on 2022-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0008_alter_emmodels_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='btdetail',
            name='baud_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='btdetail',
            name='port',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
