# Generated by Django 4.0.4 on 2022-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0009_btdetail_baud_rate_btdetail_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btdetail',
            name='baud_rate',
        ),
        migrations.RemoveField(
            model_name='btdetail',
            name='port',
        ),
    ]
