# Generated by Django 4.0.4 on 2022-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0010_remove_btdetail_baud_rate_remove_btdetail_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSdetail',
            fields=[
                ('InvoiceNo', models.IntegerField(primary_key=True, serialize=False)),
                ('BMSType', models.CharField(default=1, max_length=200)),
                ('BMSType1', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BMSdetail',
            },
        ),
    ]
