# Generated by Django 4.0.4 on 2022-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0011_bmsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsdetail',
            name='BMSType1',
            field=models.CharField(max_length=200),
        ),
    ]
