# Generated by Django 4.0.4 on 2022-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0012_alter_bmsdetail_bmstype1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsdetail',
            name='User',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='bmsdetail',
            table='bmsdetail',
        ),
    ]
