# Generated by Django 4.0.4 on 2022-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0014_inventory_detail_delete_bmsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_detail',
            name='Bike_pack',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventory_detail',
            name='Bike_pack_qty',
            field=models.IntegerField(null=True),
        ),
    ]
