# Generated by Django 4.0.4 on 2022-06-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0015_inventory_detail_bike_pack_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory_detail',
            new_name='Inventorydetail',
        ),
    ]
