# Generated by Django 4.0.4 on 2022-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0019_alter_inventorydetail_bms_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField(null=True)),
                ('BMS_Type', models.CharField(default=1, max_length=200, null=True)),
                ('BMSType', models.CharField(max_length=200, null=True)),
                ('BMS_qty', models.IntegerField(null=True)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'bms_detail',
            },
        ),
    ]
