# Generated by Django 4.0.4 on 2022-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0020_bmsdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField(null=True)),
                ('Cell_Type', models.CharField(max_length=200, null=True)),
                ('Cell_qty', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'cell_detail',
            },
        ),
        migrations.AddField(
            model_name='bmsdetail',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
