# Generated by Django 4.0.4 on 2022-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0021_celldetail_bmsdetail_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryPackdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField(null=True)),
                ('Battery_pack', models.CharField(max_length=200, null=True)),
                ('Battery_pack_qty', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'battery_pack_detail',
            },
        ),
    ]
