# Generated by Django 4.0.4 on 2022-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0023_bikepackdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAccessorydetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField(null=True)),
                ('motor_type', models.CharField(max_length=200, null=True)),
                ('motor_qty', models.IntegerField(null=True)),
                ('controller_type', models.CharField(max_length=200, null=True)),
                ('controller_qty', models.IntegerField(null=True)),
                ('throttle', models.IntegerField(null=True)),
                ('brake', models.IntegerField(null=True)),
                ('spokes', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('DatePur', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'bike_accessory_detail',
            },
        ),
    ]
