# Generated by Django 4.0.4 on 2022-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0025_batteryaccessorydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='B_Connector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='breaker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='display',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='enclosure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='thimble',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='wire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterypackdetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='batterypackdetail',
            name='InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='brake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='controller_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='controller_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='motor_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='motor_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='spokes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='throttle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikepackdetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bikepackdetail',
            name='InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmsdetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bmsdetail',
            name='InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='celldetail',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='celldetail',
            name='InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
