# Generated by Django 4.0.4 on 2022-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0026_alter_batteryaccessorydetail_b_connector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdetail',
            name='Latitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Longitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='celldetail',
            name='User',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
