# Generated by Django 4.0.4 on 2022-06-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0027_alter_btdetail_latitude_alter_btdetail_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celldetail',
            old_name='Description',
            new_name='CellDescription',
        ),
        migrations.RenameField(
            model_name='celldetail',
            old_name='InvoiceNo',
            new_name='CellInvoiceNo',
        ),
    ]
