# Generated by Django 4.0.4 on 2022-06-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0029_rename_description_bmsdetail_bmsdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterypackdetail',
            old_name='Description',
            new_name='BatteryDescription',
        ),
        migrations.RenameField(
            model_name='batterypackdetail',
            old_name='InvoiceNo',
            new_name='BatteryInvoiceNo',
        ),
    ]
