# Generated by Django 4.0.4 on 2022-06-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0030_rename_description_batterypackdetail_batterydescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikepackdetail',
            old_name='Description',
            new_name='BikeDescription',
        ),
        migrations.RenameField(
            model_name='bikepackdetail',
            old_name='InvoiceNo',
            new_name='BikeInvoiceNo',
        ),
    ]
