# Generated by Django 4.0.4 on 2022-06-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0031_rename_description_bikepackdetail_bikedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batteryaccessorydetail',
            old_name='Description',
            new_name='Battery_Description',
        ),
        migrations.RenameField(
            model_name='batteryaccessorydetail',
            old_name='InvoiceNo',
            new_name='Battery_InvoiceNo',
        ),
        migrations.RenameField(
            model_name='bikeaccessorydetail',
            old_name='Description',
            new_name='Bike_Description',
        ),
        migrations.RenameField(
            model_name='bikeaccessorydetail',
            old_name='InvoiceNo',
            new_name='Bike_InvoiceNo',
        ),
    ]
