# Generated by Django 4.0.4 on 2022-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0032_rename_description_batteryaccessorydetail_battery_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdetail',
            name='MaxAmp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MaxVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinAmp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMaxVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMinVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Temp',
            field=models.FloatField(),
        ),
    ]
