# Generated by Django 4.0.4 on 2022-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0034_customerdetail_delete_inventorydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='Battery_InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='Bike_InvoiceNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
