# Generated by Django 4.0.4 on 2022-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0035_alter_batteryaccessorydetail_battery_invoiceno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='B_Connector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='breaker',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='enclosure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='thimble',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='wire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterypackdetail',
            name='Battery_pack_qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='brake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='controller_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='motor_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='spokes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='throttle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikepackdetail',
            name='Bike_pack_qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bmsdetail',
            name='BMS_qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='celldetail',
            name='Cell_qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='B_Connector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Battery_pack_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Bike_pack_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='brake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='breaker',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='controller_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='enclosure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='motor_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='spokes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='thimble',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='throttle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='wire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
