# Generated by Django 4.0.4 on 2022-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0037_remove_customerdetail_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='display_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
