# Generated by Django 4.0.4 on 2022-07-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0039_alter_customerdetail_bms_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='otheramount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
