# Generated by Django 4.0.4 on 2022-07-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0045_batteryaccessorydetail_b_connector_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='BMSType1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMSType2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_Type1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_Type2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_price1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_qty1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='BMS_qty2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_Type1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_Type2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_Type3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_Type4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_qty1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_qty2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_qty3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_qty4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
