# Generated by Django 4.0.4 on 2022-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0046_customerdetail_bmstype1_customerdetail_bmstype2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celldetail',
            name='Cell_PUP',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
