# Generated by Django 4.0.4 on 2022-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0047_celldetail_cell_pup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldetail',
            name='Cell_PUP',
            field=models.FloatField(default=0),
        ),
    ]
