# Generated by Django 4.0.4 on 2022-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0051_rename_cell_price_customerdetail_cell_pup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='Cell_pup',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='Cell_pup1',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='Cell_pup2',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='Cell_pup3',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='Cell_pup4',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Cell_price4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='B_Connector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='B_Connector_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='breaker',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='breaker_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='display_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='enclosure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='enclosure_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='thimble',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='thimble_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='wire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batteryaccessorydetail',
            name='wire_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterypackdetail',
            name='Battery_pack_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='brake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='brake_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='controller_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='controller_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='motor_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='motor_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='spokes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='spokes_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='throttle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeaccessorydetail',
            name='throttle_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MaxAmp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MaxVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinAmp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='MinVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMaxVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='SCMinVolt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='btdetail',
            name='Temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_price1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_qty1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='BMS_qty2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='B_Connector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='B_Connector_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Battery_pack_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Battery_pack_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Bike_pack_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Bike_pack_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_qty4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='brake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='brake_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='breaker',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='breaker_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='controller_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='controller_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='display',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='display_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='enclosure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='enclosure_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='motor_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='motor_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='otheramount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='spokes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='spokes_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='thimble',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='thimble_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='throttle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='throttle_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='wire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='wire_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
