# Generated by Django 4.0.4 on 2022-08-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0052_remove_customerdetail_cell_pup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='BMS_price',
            new_name='BMS_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='BMS_price1',
            new_name='BMS_pup1',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='BMS_price2',
            new_name='BMS_pup2',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Cell_price',
            new_name='Cell_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Cell_price1',
            new_name='Cell_pup1',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Cell_price2',
            new_name='Cell_pup2',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Cell_price3',
            new_name='Cell_pup3',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Cell_price4',
            new_name='Cell_pup4',
        ),
    ]
