# Generated by Django 4.0.4 on 2022-08-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0053_rename_bms_price_customerdetail_bms_pup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='B_Connector_price',
            new_name='B_Connector_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Battery_pack_price',
            new_name='Battery_pack_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='Bike_pack_price',
            new_name='Bike_pack_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='brake_price',
            new_name='brake_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='breaker_price',
            new_name='breaker_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='controller_price',
            new_name='controller_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='display_price',
            new_name='display_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='enclosure_price',
            new_name='enclosure_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='motor_price',
            new_name='motor_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='spokes_price',
            new_name='spokes_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='thimble_price',
            new_name='thimble_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='throttle_price',
            new_name='throttle_pup',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='wire_price',
            new_name='wire_pup',
        ),
    ]
