# Generated by Django 4.0.4 on 2022-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0055_rename_price_customerdetail_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='taxamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
