# Generated by Django 4.0.4 on 2022-08-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0065_alter_customerdetail_cell_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='Cell_pup',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
