# Generated by Django 4.0.4 on 2022-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMWeb', '0071_alter_customerdetail_bms_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='DatePur',
            field=models.DateTimeField(),
        ),
    ]
